### ISSUE TITLE
weird symbols before/after names 

### ISSUE THREAD

**Issue by Alle2424** [Ritsu-Projects/Public-Releases#1]
<img width="1440" alt="Screen Shot 2021-09-12 at 4 14 12 am" src="https://user-images.githubusercontent.com/90526182/132957439-2e04647c-8812-4b7b-8e61-961a414d64fd.png">

**Comment by itsnotlupus** [comment]
Howdy! Can you provide a few more details?

- when you go to GC, are you seeing emojis after each room name in the list?
- what OS/browser are you using?
-might you be overriding the default page charset somehow, perhaps with an extension?

**Comment by Alle2424** [comment]
heyy sorry for the late reply and
- yes i am seeing emojies after each room name list.
- im using google chrome on a mac
- the only extension ive got active is tampermonkey which i use to run RxE

**Comment by ebg41** [comment]
Nobody reporting this for several months, closing
